#!/usr/bin/env node
/**
 * agentmesh installer for OpenCodex.
 *
 * OpenCodex loads plugins as plain .js files from ~/.open-codex/plugins/,
 * one tool per file, default-exporting { definition, handler }. There is no
 * package manager or config channel for plugins there, so this installer
 * generates four tiny stub files that re-export from agentmesh's OpenCodex
 * entry module.
 *
 * Usage:
 *   node scripts/install-codex.mjs [--plugins-dir <dir>] [--entry <file>]
 *
 * --plugins-dir  target directory (default: ~/.open-codex/plugins)
 * --entry        absolute path to agentmesh's codex entry (src/codex.ts).
 *                Default: resolved relative to this repo checkout.
 */

import { mkdir, writeFile } from "node:fs/promises"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

const scriptDir = dirname(fileURLToPath(import.meta.url))
const repoRoot = resolve(scriptDir, "..")

function argValue(name, fallback) {
  const argv = process.argv
  for (let i = 0; i < argv.length - 1; i++) {
    if (argv[i] === name) return argv[i + 1]
  }
  return fallback
}

const pluginsDir = argValue("--plugins-dir", `${process.env.HOME}/.open-codex/plugins`)
const entry = argValue("--entry", resolve(repoRoot, "src/codex.ts"))

const STUBS = [
  ["agentmesh-send.js", "send"],
  ["agentmesh-history.js", "history"],
  ["agentmesh-peers.js", "peers"],
  ["agentmesh-whoami.js", "whoami"],
]

// Resolve the entry as a file:// URL so ESM imports work regardless of cwd.
const entryUrl = `file://${entry.split("/").map(encodeURIComponent).join("/")}`.replace(
  /%2F/g,
  "/",
)

const TEMPLATE = (tool) => `/**
 * agentmesh (https://github.com/samooth/agentmesh) — OpenCodex plugin stub.
 * Generated by scripts/install-codex.mjs; safe to delete and regenerate.
 * Configure via AGENTMESH_ROOM / AGENTMESH_SECRET / AGENTMESH_ALLOW env vars.
 */
import { buildDefinitions, handlers } from ${JSON.stringify(entryUrl)}

export default {
  definition: buildDefinitions().${tool},
  handler: handlers.${tool},
}
`

await mkdir(pluginsDir, { recursive: true })
for (const [file, tool] of STUBS) {
  await writeFile(`${pluginsDir}/${file}`, TEMPLATE(tool), "utf8")
  console.log(`wrote ${pluginsDir}/${file}`)
}
console.log(`\nagentmesh tools installed for OpenCodex.`)
console.log(`Set AGENTMESH_ROOM (and AGENTMESH_SECRET for non-public rooms) before starting open-codex.`)
